name: Akordio

services:
  frontend:
    build:
      context: ./Frontend/Akordio_frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - VITE_API_BASE_URL=http://backend:5000
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - backend 
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - audio_temp:/tmp/akordio_audio
    environment:
      - CELERY_WORKER=false
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - CELERY_METADATA_URL=redis://redis:6379/2
    depends_on:
      - redis
  celery-annotation:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: celery_annotation_worker
    command: celery -A run.celery_app worker -l INFO --max-tasks-per-child=10 --pool=prefork --concurrency=1 --queues=annotation
    volumes:
      - audio_temp:/tmp/akordio_audio
    environment:
      - CELERY_WORKER=true
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - CELERY_METADATA_URL=redis://redis:6379/2
    depends_on:
      - backend
      - redis
  celery-separation:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: celery_separation_worker
    command: celery -A run.celery_app worker -l INFO --max-tasks-per-child=10 --pool=prefork --concurrency=1 --queues=separation
    volumes:
      - audio_temp:/tmp/akordio_audio
    environment:
      - CELERY_WORKER=true
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - CELERY_METADATA_URL=redis://redis:6379/2
    depends_on:
      - backend
      - redis
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  audio_temp: