name: Akordio

services:
  frontend:
    build:
      context: ./Frontend/Akordio_frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - VITE_API_BASE_URL=http://backend:5000
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - backend 
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    # Only for dev (live changes)
    volumes:
      - ./Backend:/backend
      - audio_temp:/tmp/akordio_audio
    environment:
      - CELERY_WORKER=false
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1 
    depends_on:
      - redis
  celery:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name:  celery_worker
    command: celery -A run.celery_app worker -l INFO --pool=solo
    volumes:
      - ./Backend:/backend
      - audio_temp:/tmp/akordio_audio
    environment:
      - CELERY_WORKER=true
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - backend
      - redis
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  audio_temp: